### PR TITLE
Upgrade resource mgmt sdk from t1 to t2

### PR DESCRIPTION
**Pull request by v-xuto**
1. Upgrade resource mgmt sdk from t1 to t2.
2. Updated files:
    1) README.md 
    2) example.py 
    3) requirements.txt 

@jameszliao-msft, @lmazuel and @jongio for notification.

### CODE REVIEW

**Comment by v-xuto** [comment]
@jongio - Can you help ping the corresponding person to review this PR?

**Comment by v-xuto** [comment]
@jameszliao-msft, @lmazuel  Could you please review this PR?

**Comment by v-xuto** [comment]
@jameszliao-msft, @lmazuel Could you please review this PR?

**Comment by v-xuto** [comment]
@jameszliao-msft, @lmazuel Could you please review this PR?

**Comment by v-xuto** [comment]
@jameszliao-msft, @lmazuel Could you please review this PR?

**Review by lmazuel — APPROVED** [review]

**Comment by lmazuel** [comment]
I don't have permission to merge

**Comment by v-xuto** [comment]
@lmazuel Okay. Thanks for your help. I will ask Jon to help merge this PR.

**Pull request merged**
